// CineVerse Mock Data Store & Offline Fallback Catalog

export const PLATFORMS = [
  { id: 'netflix', name: 'Netflix', logo: '🔴' },
  { id: 'prime', name: 'Prime Video', logo: '🔵' },
  { id: 'disney', name: 'Disney+', logo: '⭐' },
  { id: 'apple', name: 'Apple TV+', logo: '🍏' },
  { id: 'mubi', name: 'Mubi', logo: '🌀' },
  { id: 'hbo', name: 'HBO Max', logo: '🟣' }
];

export const MOODS = [
  { id: 'mind_bending', name: 'Mind-bending', icon: '🧠', desc: 'Expect the unexpected and question reality.' },
  { id: 'fun_light', name: 'Fun and light', icon: '🍿', desc: 'Easy watches, laughs, and good vibes.' },
  { id: 'good_cry', name: 'Need a good cry', icon: '😭', desc: 'Emotional rollercoasters and deep dramas.' },
  { id: 'action_packed', name: 'Action-packed', icon: '💥', desc: 'High adrenaline, fights, and fast paces.' },
  { id: 'slow_burn', name: 'Intense slow-burn', icon: '⏳', desc: 'Atmospheric, psychological, and rewarding.' },
  { id: 'feel_good', name: 'Warm & Feel-good', icon: '✨', desc: 'Heartwarming stories that leave you smiling.' }
];

export const GENRES = [
  'Sci-Fi', 'Thriller', 'Drama', 'Romance', 'Action', 'Indie', 'Comedy', 'Anime', 'Mystery', 'Horror', 'Biography', 'Crime', 'Sport', 'History'
];

export const MOCK_MOVIES = [
  // --- Hollywood (1 to 10) ---
  {
    id: 1,
    title: "Interstellar",
    type: "movie",
    year: 2014,
    runtime: "169 min",
    genres: ["Sci-Fi", "Drama", "Mystery"],
    languages: ["English", "Hindi"],
    imdbRating: 8.7,
    rtRating: "73%",
    cineverseRating: 9.2,
    synopsis: "In Earth's future, a global crop blight and second Dust Bowl are slowly rendering the planet uninhabitable. Professor Brand, a brilliant NASA physicist, is working on plans to save mankind by transporting Earth's population to a new home via a wormhole.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/xJHok7RjqyOK9m24JjZu7VFBp5m.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/gEU2Qv4ilfg7ax3Jv1v24B7C0z3.jpg",
    moods: ["mind_bending", "good_cry", "slow_burn"],
    platforms: [
      { id: "netflix", name: "Netflix", price: "Subscription", available: true },
      { id: "prime", name: "Prime Video", price: "Rent ₹120", available: true },
      { id: "apple", name: "Apple TV+", price: "Buy ₹490", available: true }
    ],
    cast: [
      { name: "Matthew McConaughey", role: "Cooper", img: "https://image.tmdb.org/t/p/w185/eUiRli4u44Bs2n4U56Egfd48Q1m.jpg" },
      { name: "Anne Hathaway", role: "Brand", img: "https://image.tmdb.org/t/p/w185/4lhbj7hJ14nnSRR4vQt482a45jC.jpg" },
      { name: "Jessica Chastain", role: "Murph", img: "https://image.tmdb.org/t/p/w185/914Qh212vJSDqgOphF4dZ1oG7V0.jpg" }
    ],
    trailerId: "zSWdZVtXT7U",
    industry: "hollywood"
  },
  {
    id: 2,
    title: "Inception",
    type: "movie",
    year: 2010,
    runtime: "148 min",
    genres: ["Sci-Fi", "Action", "Thriller"],
    languages: ["English"],
    imdbRating: 8.8,
    rtRating: "87%",
    cineverseRating: 9.3,
    synopsis: "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets, is offered a chance to regain his old life as payment for a task considered to be impossible: inception.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/8ZuznDM65FU4aa1u2RCnGrz5QDu.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/o0fgcCZdClWg7TyZmA7LIj4nw4R.jpg",
    moods: ["mind_bending", "action_packed", "slow_burn"],
    platforms: [
      { id: "netflix", name: "Netflix", price: "Subscription", available: true },
      { id: "prime", name: "Prime Video", price: "Subscription", available: true }
    ],
    cast: [
      { name: "Leonardo DiCaprio", role: "Cobb", img: "https://image.tmdb.org/t/p/w185/wo2hJv0ktj4B2IptJywG446tBc2.jpg" },
      { name: "Joseph Gordon-Levitt", role: "Arthur", img: "https://image.tmdb.org/t/p/w185/dhV95t1nptP6g0asU7u6w24ptwT.jpg" },
      { name: "Elliot Page", role: "Ariadne", img: "https://image.tmdb.org/t/p/w185/tp9w128hA2k5gNpeW69Vrcj2hWv.jpg" }
    ],
    trailerId: "YoHD9XEInc0",
    industry: "hollywood"
  },
  {
    id: 3,
    title: "The Dark Knight",
    type: "movie",
    year: 2008,
    runtime: "152 min",
    genres: ["Action", "Drama", "Thriller"],
    languages: ["English"],
    imdbRating: 9.0,
    rtRating: "94%",
    cineverseRating: 9.6,
    synopsis: "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/dqK9Hn2kr2fgZwNd6OUceH0GZAB.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/qJ2tW65GxgYwQI7cWwHmgRxiuOq.jpg",
    moods: ["action_packed", "slow_burn"],
    platforms: [
      { id: "netflix", name: "Netflix", price: "Subscription", available: true },
      { id: "disney", name: "Disney+", price: "Subscription", available: true }
    ],
    cast: [
      { name: "Christian Bale", role: "Bruce Wayne / Batman", img: "https://image.tmdb.org/t/p/w185/b7fTCwq6saTxH6v6qV4nv7wD7ah.jpg" },
      { name: "Heath Ledger", role: "Joker", img: "https://image.tmdb.org/t/p/w185/aa6m1lSFS58nd61vA8959tV4i5n.jpg" },
      { name: "Aaron Eckhart", role: "Harvey Dent", img: "https://image.tmdb.org/t/p/w185/j565J9ipLI852p4G4H2j1nLp267.jpg" }
    ],
    trailerId: "LDG9bisJEaI",
    industry: "hollywood"
  },
  {
    id: 4,
    title: "Dune: Part Two",
    type: "movie",
    year: 2024,
    runtime: "166 min",
    genres: ["Sci-Fi", "Action", "Drama"],
    languages: ["English", "Hindi"],
    imdbRating: 8.9,
    rtRating: "95%",
    cineverseRating: 9.5,
    synopsis: "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/xOM0868K6q57wcwJVa4cLftIX4x.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/czemZb0V722R89IHnJgKz28bLr6.jpg",
    moods: ["action_packed", "slow_burn"],
    platforms: [
      { id: "netflix", name: "Netflix", price: "Subscription", available: true },
      { id: "prime", name: "Prime Video", price: "Rent ₹150", available: true }
    ],
    cast: [
      { name: "Timothée Chalamet", role: "Paul Atreides", img: "https://image.tmdb.org/t/p/w185/BE7ZpS1f9G8v1447H047r6T.jpg" },
      { name: "Zendaya", role: "Chani", img: "https://image.tmdb.org/t/p/w185/7414K68q9vKz941G0fC0T.jpg" },
      { name: "Rebecca Ferguson", role: "Lady Jessica", img: "https://image.tmdb.org/t/p/w185/104e760a7F0Jb1129fC0.jpg" }
    ],
    trailerId: "Way9Dexny3w",
    industry: "hollywood"
  },
  {
    id: 5,
    title: "Oppenheimer",
    type: "movie",
    year: 2023,
    runtime: "180 min",
    genres: ["Drama", "History", "Biography"],
    languages: ["English"],
    imdbRating: 8.6,
    rtRating: "93%",
    cineverseRating: 9.2,
    synopsis: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/nbKzGgYxLwMh3kZex7wTUXxMvT.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/8Gxv2wSbsCxR08krUgEBwbIqjSy.jpg",
    moods: ["slow_burn", "good_cry"],
    platforms: [
      { id: "prime", name: "Prime Video", price: "Subscription", available: true },
      { id: "netflix", name: "Netflix", price: "Subscription", available: true }
    ],
    cast: [
      { name: "Cillian Murphy", role: "J. Robert Oppenheimer", img: "https://image.tmdb.org/t/p/w185/llmZ2k3Dwbw.jpg" },
      { name: "Emily Blunt", role: "Kitty Oppenheimer", img: "https://image.tmdb.org/t/p/w185/EmilyBlunt.jpg" }
    ],
    trailerId: "uYPbbksJxIg",
    industry: "hollywood"
  },
  {
    id: 6,
    title: "Avatar",
    type: "movie",
    year: 2009,
    runtime: "162 min",
    genres: ["Sci-Fi", "Action", "Adventure"],
    languages: ["English"],
    imdbRating: 7.9,
    rtRating: "82%",
    cineverseRating: 8.4,
    synopsis: "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/vL526bAl133J0vh87474413ebS.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/kyeqWzo2vO9EXga60Y01m0CebR.jpg",
    moods: ["action_packed", "fun_light"],
    platforms: [{ id: "disney", name: "Disney+", price: "Subscription", available: true }],
    cast: [{ name: "Sam Worthington", role: "Jake Sully", img: "https://image.tmdb.org/t/p/w185/SamW.jpg" }],
    trailerId: "5PSNL1q3fcM",
    industry: "hollywood"
  },
  {
    id: 7,
    title: "Gladiator",
    type: "movie",
    year: 2000,
    runtime: "155 min",
    genres: ["Action", "Adventure", "Drama"],
    languages: ["English"],
    imdbRating: 8.5,
    rtRating: "80%",
    cineverseRating: 9.0,
    synopsis: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/wS6XhWn21c60HwPZpx9XGzVUXN9.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/ty8hDC784fQoVufg47gEK7Esclz.jpg",
    moods: ["action_packed", "good_cry"],
    platforms: [{ id: "netflix", name: "Netflix", price: "Subscription", available: true }],
    cast: [{ name: "Russell Crowe", role: "Maximus", img: "https://image.tmdb.org/t/p/w185/Russell.jpg" }],
    trailerId: "P5ieIbInFpg",
    industry: "hollywood"
  },
  {
    id: 8,
    title: "Titanic",
    type: "movie",
    year: 1997,
    runtime: "194 min",
    genres: ["Drama", "Romance"],
    languages: ["English"],
    imdbRating: 7.9,
    rtRating: "88%",
    cineverseRating: 8.5,
    synopsis: "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/6ZZ4n65GxgYwQI7cWwHmgRxiuOq.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/9xj7v4rV42ZqN36585g309ES153.jpg",
    moods: ["good_cry", "slow_burn"],
    platforms: [{ id: "disney", name: "Disney+", price: "Subscription", available: true }],
    cast: [{ name: "Leonardo DiCaprio", role: "Jack Dawson", img: "https://image.tmdb.org/t/p/w185/wo2hJv0ktj4B2IptJywG446tBc2.jpg" }],
    trailerId: "CHekzSiZ47I",
    industry: "hollywood"
  },
  {
    id: 9,
    title: "The Matrix",
    type: "movie",
    year: 1999,
    runtime: "136 min",
    genres: ["Sci-Fi", "Action"],
    languages: ["English"],
    imdbRating: 8.7,
    rtRating: "88%",
    cineverseRating: 9.3,
    synopsis: "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/l3rhl9XsiPT76M23jV9N2vN6.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/f89U3wzqrjVmq66G2y2uXXn4mZ7.jpg",
    moods: ["mind_bending", "action_packed"],
    platforms: [{ id: "netflix", name: "Netflix", price: "Subscription", available: true }],
    cast: [{ name: "Keanu Reeves", role: "Neo", img: "https://image.tmdb.org/t/p/w185/Keanu.jpg" }],
    trailerId: "m8e-FF8MsqU",
    industry: "hollywood"
  },
  {
    id: 10,
    title: "Avengers: Endgame",
    type: "movie",
    year: 2019,
    runtime: "181 min",
    genres: ["Action", "Sci-Fi", "Adventure"],
    languages: ["English"],
    imdbRating: 8.4,
    rtRating: "94%",
    cineverseRating: 9.1,
    synopsis: "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/7RyGuZ2dYg4b2y4g67U7u6w.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/or06509kZk2u3u51Z534n8.jpg",
    moods: ["action_packed", "fun_light"],
    platforms: [{ id: "disney", name: "Disney+", price: "Subscription", available: true }],
    cast: [{ name: "Robert Downey Jr.", role: "Tony Stark", img: "https://image.tmdb.org/t/p/w185/Robert.jpg" }],
    trailerId: "TcMBFSGVi1c",
    industry: "hollywood"
  },

  // --- Bollywood (11 to 20) ---
  {
    id: 11,
    title: "3 Idiots",
    type: "movie",
    year: 2009,
    runtime: "170 min",
    genres: ["Comedy", "Drama"],
    languages: ["Hindi", "English"],
    imdbRating: 8.4,
    rtRating: "90%",
    cineverseRating: 9.2,
    synopsis: "Two friends are searching for their long lost companion. They revisit their college days and recall the memories of their friend who inspired them to think differently, even as the rest of the world called them 'idiots'.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/u2cA36Z5y50Dwb64V76R0ge54.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/66474413ebS9xj7v4rV42ZqN365.jpg",
    moods: ["feel_good", "fun_light", "good_cry"],
    platforms: [
      { id: "netflix", name: "Netflix", price: "Subscription", available: true },
      { id: "prime", name: "Prime Video", price: "Subscription", available: true }
    ],
    cast: [
      { name: "Aamir Khan", role: "Rancho", img: "https://image.tmdb.org/t/p/w185/5Lg50D270Q.jpg" },
      { name: "R. Madhavan", role: "Farhan", img: "https://image.tmdb.org/t/p/w185/Madhavan.jpg" }
    ],
    trailerId: "K0eDlFX9GMc",
    industry: "bollywood"
  },
  {
    id: 12,
    title: "Dangal",
    type: "movie",
    year: 2016,
    runtime: "161 min",
    genres: ["Drama", "Biography", "Action", "Sport"],
    languages: ["Hindi"],
    imdbRating: 8.4,
    rtRating: "88%",
    cineverseRating: 9.3,
    synopsis: "Mahavir Singh Phogat, a former wrestler, decides to fulfill his dream of winning a gold medal for his country by training his daughters Geeta and Babita to become world-class wrestlers.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/70ge54u2cA36Z5y50Dwb64V76R0.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/7456DdaYQh0Z6jL3R6qnEu8H1w.jpg",
    moods: ["feel_good", "good_cry", "action_packed"],
    platforms: [{ id: "netflix", name: "Netflix", price: "Subscription", available: true }],
    cast: [{ name: "Aamir Khan", role: "Mahavir Singh Phogat", img: "https://image.tmdb.org/t/p/w185/5Lg50D270Q.jpg" }],
    trailerId: "x_7YlGv9u1g",
    industry: "bollywood"
  },
  {
    id: 13,
    title: "Sholay",
    type: "movie",
    year: 1975,
    runtime: "204 min",
    genres: ["Action", "Adventure", "Comedy"],
    languages: ["Hindi"],
    imdbRating: 8.2,
    rtRating: "92%",
    cineverseRating: 8.9,
    synopsis: "After his family is murdered by a notorious bandit named Gabbar Singh, a retired police officer recruits two small-time convicts to capture him.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/wVufg47gEK7Esclzty8hDC784f.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/2vO9EXga60Y01m0CebRkyeQWzo.jpg",
    moods: ["action_packed", "fun_light"],
    platforms: [{ id: "prime", name: "Prime Video", price: "Subscription", available: true }],
    cast: [{ name: "Amitabh Bachchan", role: "Jai", img: "https://image.tmdb.org/t/p/w185/Amitabh.jpg" }],
    trailerId: "de_5k_BvOsk",
    industry: "bollywood"
  },
  {
    id: 14,
    title: "Jawan",
    type: "movie",
    year: 2023,
    runtime: "168 min",
    genres: ["Action", "Thriller"],
    languages: ["Hindi", "Tamil", "Telugu"],
    imdbRating: 7.8,
    rtRating: "85%",
    cineverseRating: 8.2,
    synopsis: "A personal grudge drives a man to settle scores with a ruthless arms dealer, while attempting to correct the wrongs of society and fulfill a promise made years ago.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/lPT76M23jV9N2vN6l3rhl9XsiPT.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/1s85g309ES1539xj7v4rV42ZqN3.jpg",
    moods: ["action_packed", "mind_bending"],
    platforms: [{ id: "netflix", name: "Netflix", price: "Subscription", available: true }],
    cast: [{ name: "Shah Rukh Khan", role: "Vikram Rathore", img: "https://image.tmdb.org/t/p/w185/SRK.jpg" }],
    trailerId: "COv527TEy64",
    industry: "bollywood"
  },
  {
    id: 15,
    title: "Zindagi Na Milegi Dobara",
    type: "movie",
    year: 2011,
    runtime: "155 min",
    genres: ["Comedy", "Drama", "Romance"],
    languages: ["Hindi"],
    imdbRating: 8.2,
    rtRating: "91%",
    cineverseRating: 8.8,
    synopsis: "Three friends decide to turn their fantasy bachelor road trip in Spain into reality after one of them gets engaged.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/aa8959tV4i5naa6m1lSFS58nd61.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/y94nv7wD7ahb7fTCwq6saTxH6v.jpg",
    moods: ["feel_good", "fun_light"],
    platforms: [{ id: "netflix", name: "Netflix", price: "Subscription", available: true }],
    cast: [{ name: "Hrithik Roshan", role: "Arjun", img: "https://image.tmdb.org/t/p/w185/Hrithik.jpg" }],
    trailerId: "NX7N1w26Z8E",
    industry: "bollywood"
  },
  {
    id: 16,
    title: "Dilwale Dulhania Le Jayenge",
    type: "movie",
    year: 1995,
    runtime: "189 min",
    genres: ["Drama", "Romance", "Comedy"],
    languages: ["Hindi"],
    imdbRating: 8.3,
    rtRating: "93%",
    cineverseRating: 9.0,
    synopsis: "Raj and Simran meet on a trip through Europe. Simran falls in love with him but her conservative father has already promised her hand to another in India.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/81szTId4g9V035w3UaZ6lE1X7n0.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/uC6TTpg4tU75Y07CVS1THe71Sl.jpg",
    moods: ["feel_good", "good_cry"],
    platforms: [{ id: "prime", name: "Prime Video", price: "Subscription", available: true }],
    cast: [{ name: "Shah Rukh Khan", role: "Raj", img: "https://image.tmdb.org/t/p/w185/SRK.jpg" }],
    trailerId: "c25GKl5VNeY",
    industry: "bollywood"
  },
  {
    id: 17,
    title: "Gangs of Wasseypur",
    type: "movie",
    year: 2012,
    runtime: "321 min",
    genres: ["Action", "Crime", "Drama"],
    languages: ["Hindi"],
    imdbRating: 8.2,
    rtRating: "96%",
    cineverseRating: 9.2,
    synopsis: "A clash between Sultan and Shahid Khan leads to the expulsion of Shahid Khan from Wasseypur, igniting a deadly multi-generational coal mafia feud.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/b7TCwq6saTxH6v6qV4nv7wD7ah.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/j52p4G4H2j1nLp26765J9ipLI85.jpg",
    moods: ["slow_burn", "action_packed"],
    platforms: [{ id: "netflix", name: "Netflix", price: "Subscription", available: true }],
    cast: [{ name: "Manoj Bajpayee", role: "Sardar Khan", img: "https://image.tmdb.org/t/p/w185/Manoj.jpg" }],
    trailerId: "j-AkWDkXcMY",
    industry: "bollywood"
  },
  {
    id: 18,
    title: "Pathaan",
    type: "movie",
    year: 2023,
    runtime: "146 min",
    genres: ["Action", "Thriller"],
    languages: ["Hindi"],
    imdbRating: 7.0,
    rtRating: "82%",
    cineverseRating: 7.5,
    synopsis: "An Indian agent comes out of exile to stop a rogue military group planning to launch a bio-weapon attack on India.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/lksd8.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/i9l0U.jpg",
    moods: ["action_packed", "fun_light"],
    platforms: [{ id: "prime", name: "Prime Video", price: "Subscription", available: true }],
    cast: [{ name: "Shah Rukh Khan", role: "Pathaan", img: "https://image.tmdb.org/t/p/w185/SRK.jpg" }],
    trailerId: "vqu4z34wEN8",
    industry: "bollywood"
  },
  {
    id: 19,
    title: "Bajrangi Bhaijaan",
    type: "movie",
    year: 2015,
    runtime: "163 min",
    genres: ["Comedy", "Drama", "Action"],
    languages: ["Hindi"],
    imdbRating: 8.1,
    rtRating: "100%",
    cineverseRating: 8.7,
    synopsis: "A warm-hearted Indian man takes a young mute Pakistani girl back to her homeland to reunite her with her family.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/bajrangiback.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/bajrangi.jpg",
    moods: ["feel_good", "good_cry"],
    platforms: [{ id: "disney", name: "Disney+", price: "Subscription", available: true }],
    cast: [{ name: "Salman Khan", role: "Pawan", img: "https://image.tmdb.org/t/p/w185/Salman.jpg" }],
    trailerId: "4nwArEscLfk",
    industry: "bollywood"
  },
  {
    id: 20,
    title: "Barfi!",
    type: "movie",
    year: 2012,
    runtime: "151 min",
    genres: ["Comedy", "Drama", "Romance"],
    languages: ["Hindi"],
    imdbRating: 8.1,
    rtRating: "92%",
    cineverseRating: 8.8,
    synopsis: "Three young people learn that love can neither be defined nor contained by society's definition of normal and abnormal.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/barfiback.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/barfi.jpg",
    moods: ["feel_good", "good_cry", "fun_light"],
    platforms: [{ id: "netflix", name: "Netflix", price: "Subscription", available: true }],
    cast: [{ name: "Ranbir Kapoor", role: "Barfi", img: "https://image.tmdb.org/t/p/w185/Ranbir.jpg" }],
    trailerId: "yZHEN3mDBh0",
    industry: "bollywood"
  },

  // --- Tollywood (21 to 30) ---
  {
    id: 21,
    title: "Baahubali: The Beginning",
    type: "movie",
    year: 2015,
    runtime: "159 min",
    genres: ["Action", "Drama", "Fantasy"],
    languages: ["Telugu", "Tamil", "Hindi"],
    imdbRating: 8.0,
    rtRating: "87%",
    cineverseRating: 8.8,
    synopsis: "In ancient Kingdom of Mahishmati, a child is raised by commoners and grows up to be a strong man, discovering his noble lineage and preparing to confront a tyrannical king.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/t558nCxQv74JTY1I1ExuYq5J2Gi.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/z45HiuN4r764bwhqH6Pj466L61C.jpg",
    moods: ["action_packed", "mind_bending"],
    platforms: [
      { id: "netflix", name: "Netflix", price: "Subscription", available: true },
      { id: "disney", name: "Disney+", price: "Subscription", available: true }
    ],
    cast: [
      { name: "Prabhas", role: "Baahubali", img: "https://image.tmdb.org/t/p/w185/Prabhas.jpg" },
      { name: "Rana Daggubati", role: "Bhallaladeva", img: "https://image.tmdb.org/t/p/w185/Rana.jpg" }
    ],
    trailerId: "sOEg_YZQsTI",
    industry: "tollywood"
  },
  {
    id: 22,
    title: "RRR",
    type: "movie",
    year: 2022,
    runtime: "187 min",
    genres: ["Action", "Drama"],
    languages: ["Telugu", "Tamil", "Hindi"],
    imdbRating: 8.0,
    rtRating: "95%",
    cineverseRating: 9.4,
    synopsis: "A fictional history of two legendary revolutionaries' journey away from home before they began fighting for their country in the 1920s.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/70ge54u2cA36Z5y50Dwb64V76R0.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/nEu8H1w73456DdaYQh0Z6jL3R6q.jpg",
    moods: ["action_packed", "feel_good", "good_cry"],
    platforms: [
      { id: "netflix", name: "Netflix", price: "Subscription", available: true },
      { id: "prime", name: "Prime Video", price: "Subscription", available: true }
    ],
    cast: [
      { name: "N.T. Rama Rao Jr.", role: "Bheem", img: "https://image.tmdb.org/t/p/w185/NTR.jpg" },
      { name: "Ram Charan", role: "Raju", img: "https://image.tmdb.org/t/p/w185/RamCharan.jpg" }
    ],
    trailerId: "NgBoMJy386M",
    industry: "tollywood"
  },
  {
    id: 23,
    title: "Pushpa: The Rise",
    type: "movie",
    year: 2021,
    runtime: "179 min",
    genres: ["Action", "Crime", "Drama"],
    languages: ["Telugu", "Hindi", "Tamil"],
    imdbRating: 7.6,
    rtRating: "80%",
    cineverseRating: 8.1,
    synopsis: "Violence erupts between red sandalwood smugglers and the police in the Seshachalam forests of Andhra Pradesh, as coolie Pushpa Raj rises to rule the syndicate.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/pushpaback.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/pushpa.jpg",
    moods: ["action_packed", "slow_burn"],
    platforms: [{ id: "prime", name: "Prime Video", price: "Subscription", available: true }],
    cast: [{ name: "Allu Arjun", role: "Pushpa Raj", img: "https://image.tmdb.org/t/p/w185/AlluArjun.jpg" }],
    trailerId: "pKctjlxbFDQ",
    industry: "tollywood"
  },
  {
    id: 24,
    title: "Kalki 2898 AD",
    type: "movie",
    year: 2024,
    runtime: "180 min",
    genres: ["Sci-Fi", "Action", "Adventure"],
    languages: ["Telugu", "Hindi", "Tamil"],
    imdbRating: 7.7,
    rtRating: "85%",
    cineverseRating: 8.8,
    synopsis: "A modern avatar of Vishnu, a Hindu god, is believed to have descended to Earth to protect the world from evil forces in a futuristic setting.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/kalkiback.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/kalki.jpg",
    moods: ["mind_bending", "action_packed"],
    platforms: [
      { id: "netflix", name: "Netflix", price: "Subscription", available: true },
      { id: "prime", name: "Prime Video", price: "Subscription", available: true }
    ],
    cast: [{ name: "Prabhas", role: "Bhairava", img: "https://image.tmdb.org/t/p/w185/Prabhas.jpg" }],
    trailerId: "L3oOldViMxY",
    industry: "tollywood"
  },
  {
    id: 25,
    title: "Salaar: Ceasefire",
    type: "movie",
    year: 2023,
    runtime: "175 min",
    genres: ["Action", "Thriller"],
    languages: ["Telugu", "Hindi", "Kannada"],
    imdbRating: 6.9,
    rtRating: "70%",
    cineverseRating: 7.4,
    synopsis: "A gang leader makes a promise to a dying friend and takes on other criminal gangs.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/salaarback.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/salaar.jpg",
    moods: ["action_packed", "slow_burn"],
    platforms: [{ id: "netflix", name: "Netflix", price: "Subscription", available: true }],
    cast: [{ name: "Prabhas", role: "Deva / Salaar", img: "https://image.tmdb.org/t/p/w185/Prabhas.jpg" }],
    trailerId: "4GPvYV_Z4L8",
    industry: "tollywood"
  },
  {
    id: 26,
    title: "Magadheera",
    type: "movie",
    year: 2009,
    runtime: "166 min",
    genres: ["Action", "Drama", "Fantasy"],
    languages: ["Telugu"],
    imdbRating: 7.7,
    rtRating: "83%",
    cineverseRating: 8.5,
    synopsis: "A bike stuntman recalls his previous life as a warrior in 17th century Rajasthan, trying to save his princess and defeat a corrupt military commander.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/magadheeraback.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/magadheera.jpg",
    moods: ["action_packed", "good_cry"],
    platforms: [{ id: "disney", name: "Disney+", price: "Subscription", available: true }],
    cast: [{ name: "Ram Charan", role: "Kala Bhairava", img: "https://image.tmdb.org/t/p/w185/RamCharan.jpg" }],
    trailerId: "wGZ82rV8e4A",
    industry: "tollywood"
  },
  {
    id: 27,
    title: "Arjun Reddy",
    type: "movie",
    year: 2017,
    runtime: "182 min",
    genres: ["Drama", "Romance"],
    languages: ["Telugu"],
    imdbRating: 8.0,
    rtRating: "85%",
    cineverseRating: 8.7,
    synopsis: "Arjun Reddy, a short-tempered house surgeon, gets habituated to drugs and alcohol when his girlfriend is forced to marry another person.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/arjunreddyback.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/arjunreddy.jpg",
    moods: ["good_cry", "slow_burn"],
    platforms: [{ id: "disney", name: "Disney+", price: "Subscription", available: true }],
    cast: [{ name: "Vijay Deverakonda", role: "Arjun Reddy", img: "https://image.tmdb.org/t/p/w185/Vijay.jpg" }],
    trailerId: "aozWq_W-D8M",
    industry: "tollywood"
  },
  {
    id: 28,
    title: "Jersey",
    type: "movie",
    year: 2019,
    runtime: "140 min",
    genres: ["Drama", "Sport"],
    languages: ["Telugu"],
    imdbRating: 8.5,
    rtRating: "96%",
    cineverseRating: 9.2,
    synopsis: "A failed cricketer decides to revive his career in his late thirties, driven by the desire to fulfill his son's wish for a jersey as a gift.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/jerseyback.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/jersey.jpg",
    moods: ["feel_good", "good_cry"],
    platforms: [{ id: "disney", name: "Disney+", price: "Subscription", available: true }],
    cast: [{ name: "Nani", role: "Arjun", img: "https://image.tmdb.org/t/p/w185/Nani.jpg" }],
    trailerId: "R4vEupFEtkY",
    industry: "tollywood"
  },
  {
    id: 29,
    title: "Devara: Part 1",
    type: "movie",
    year: 2024,
    runtime: "177 min",
    genres: ["Action", "Drama", "Thriller"],
    languages: ["Telugu", "Hindi", "Tamil"],
    imdbRating: 7.2,
    rtRating: "78%",
    cineverseRating: 7.9,
    synopsis: "An epic action saga set in coastal lands, chronicling dynamic characters and battles against dark smuggling networks.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/devaraback.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/devara.jpg",
    moods: ["action_packed", "slow_burn"],
    platforms: [{ id: "netflix", name: "Netflix", price: "Subscription", available: true }],
    cast: [{ name: "N.T. Rama Rao Jr.", role: "Devara", img: "https://image.tmdb.org/t/p/w185/NTR.jpg" }],
    trailerId: "aG-Qc4G1B1g",
    industry: "tollywood"
  },
  {
    id: 30,
    title: "Eega",
    type: "movie",
    year: 2012,
    runtime: "145 min",
    genres: ["Action", "Comedy", "Fantasy"],
    languages: ["Telugu", "Tamil", "Hindi"],
    imdbRating: 7.7,
    rtRating: "85%",
    cineverseRating: 8.6,
    synopsis: "A murdered man is reincarnated as a housefly and seeks to avenge his death and protect his love from the villain who killed him.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/eegaback.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/eega.jpg",
    moods: ["action_packed", "fun_light"],
    platforms: [{ id: "disney", name: "Disney+", price: "Subscription", available: true }],
    cast: [{ name: "Sudeep", role: "Sudeep", img: "https://image.tmdb.org/t/p/w185/Sudeep.jpg" }],
    trailerId: "3lR_N3k4xYk",
    industry: "tollywood"
  },

  // --- Webseries (31 to 40) ---
  {
    id: 31,
    title: "Stranger Things",
    type: "series",
    year: 2016,
    runtime: "4 Seasons",
    genres: ["Sci-Fi", "Drama", "Mystery"],
    languages: ["English", "Hindi"],
    imdbRating: 8.7,
    rtRating: "92%",
    cineverseRating: 9.3,
    synopsis: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/56v2Kj2q2zsOVj3tX7zGwtmY8f6.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/x2Lw3ku51Z534nor06509kZk2u3.jpg",
    moods: ["mind_bending", "action_packed"],
    platforms: [{ id: "netflix", name: "Netflix", price: "Subscription", available: true }],
    cast: [
      { name: "Millie Bobby Brown", role: "Eleven", img: "https://image.tmdb.org/t/p/w185/Millie.jpg" },
      { name: "Winona Ryder", role: "Joyce", img: "https://image.tmdb.org/t/p/w185/Winona.jpg" }
    ],
    trailerId: "b9EkMc79ZSU",
    industry: "webseries"
  },
  {
    id: 32,
    title: "Game of Thrones",
    type: "series",
    year: 2011,
    runtime: "8 Seasons",
    genres: ["Action", "Adventure", "Drama"],
    languages: ["English"],
    imdbRating: 9.2,
    rtRating: "89%",
    cineverseRating: 9.5,
    synopsis: "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for thousands of years.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/2OMB0hk21iZsVI6kg85t8u88BoI.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/1XS1nmaHZcZ24scJU4BgLIuEQcV.jpg",
    moods: ["action_packed", "slow_burn"],
    platforms: [{ id: "disney", name: "Disney+", price: "Subscription", available: true }],
    cast: [
      { name: "Emilia Clarke", role: "Daenerys", img: "https://image.tmdb.org/t/p/w185/Emilia.jpg" },
      { name: "Kit Harington", role: "Jon Snow", img: "https://image.tmdb.org/t/p/w185/Kit.jpg" }
    ],
    trailerId: "gcTkFNGeTSc",
    industry: "webseries"
  },
  {
    id: 33,
    title: "Sacred Games",
    type: "series",
    year: 2018,
    runtime: "2 Seasons",
    genres: ["Action", "Crime", "Thriller"],
    languages: ["Hindi"],
    imdbRating: 8.5,
    rtRating: "76%",
    cineverseRating: 8.8,
    synopsis: "A link in their pasts leads an honest cop to a fugitive gang boss, whose cryptic warning spurs the officer on a quest to save Mumbai from cataclysm.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/gamesback.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/775H7xI2U8G4m8h3B58J864wR2B.jpg",
    moods: ["slow_burn", "action_packed"],
    platforms: [{ id: "netflix", name: "Netflix", price: "Subscription", available: true }],
    cast: [{ name: "Saif Ali Khan", role: "Sartaj Singh", img: "https://image.tmdb.org/t/p/w185/Saif.jpg" }],
    trailerId: "28j8h0XRqQs",
    industry: "webseries"
  },
  {
    id: 34,
    title: "The Family Man",
    type: "series",
    year: 2019,
    runtime: "2 Seasons",
    genres: ["Action", "Comedy", "Drama"],
    languages: ["Hindi", "English"],
    imdbRating: 8.7,
    rtRating: "95%",
    cineverseRating: 9.2,
    synopsis: "A middle-class man secretly works as an intelligence officer for the Threat Analysis and Surveillance Cell, trying to protect the nation while keeping his family safe.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/familymanback.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/familyman.jpg",
    moods: ["action_packed", "fun_light"],
    platforms: [{ id: "prime", name: "Prime Video", price: "Subscription", available: true }],
    cast: [{ name: "Manoj Bajpayee", role: "Srikant Tiwari", img: "https://image.tmdb.org/t/p/w185/Manoj.jpg" }],
    trailerId: "XatRGut65VI",
    industry: "webseries"
  },
  {
    id: 35,
    title: "Mirzapur",
    type: "series",
    year: 2018,
    runtime: "3 Seasons",
    genres: ["Action", "Crime", "Drama"],
    languages: ["Hindi"],
    imdbRating: 8.5,
    rtRating: "85%",
    cineverseRating: 8.9,
    synopsis: "A shocking incident at a wedding procession ignites a series of events, entangling the lives of two families in the lawless city of Mirzapur.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/mirzapurback.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/mirzapur.jpg",
    moods: ["action_packed", "slow_burn"],
    platforms: [{ id: "prime", name: "Prime Video", price: "Subscription", available: true }],
    cast: [{ name: "Pankaj Tripathi", role: "Kaleen Bhaiya", img: "https://image.tmdb.org/t/p/w185/Pankaj.jpg" }],
    trailerId: "ZNeGFyY14UI",
    industry: "webseries"
  },
  {
    id: 36,
    title: "Panchayat",
    type: "series",
    year: 2020,
    runtime: "3 Seasons",
    genres: ["Comedy", "Drama"],
    languages: ["Hindi"],
    imdbRating: 8.9,
    rtRating: "96%",
    cineverseRating: 9.3,
    synopsis: "An engineering graduate takes up a job as a secretary of a Panchayat office in a remote village named Phulera, due to a lack of better job options.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/panchayatback.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/panchayat.jpg",
    moods: ["feel_good", "fun_light"],
    platforms: [{ id: "prime", name: "Prime Video", price: "Subscription", available: true }],
    cast: [{ name: "Jitendra Kumar", role: "Abhishek", img: "https://image.tmdb.org/t/p/w185/Jitendra.jpg" }],
    trailerId: "mCpeVkiZf5E",
    industry: "webseries"
  },
  {
    id: 37,
    title: "Breaking Bad",
    type: "series",
    year: 2008,
    runtime: "5 Seasons",
    genres: ["Crime", "Drama", "Thriller"],
    languages: ["English"],
    imdbRating: 9.5,
    rtRating: "96%",
    cineverseRating: 9.7,
    synopsis: "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student in order to secure his family's future.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/ts58nCxQv74JTY1I1ExuYq5J2Gi.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/ztkUQj611sR75ASj2j96mu45865.jpg",
    moods: ["slow_burn", "mind_bending"],
    platforms: [{ id: "netflix", name: "Netflix", price: "Subscription", available: true }],
    cast: [{ name: "Bryan Cranston", role: "Walter White", img: "https://image.tmdb.org/t/p/w185/Bryan.jpg" }],
    trailerId: "HhesaQXLuRY",
    industry: "webseries"
  },
  {
    id: 38,
    title: "Money Heist",
    type: "series",
    year: 2017,
    runtime: "5 Parts",
    genres: ["Action", "Crime", "Mystery"],
    languages: ["Spanish", "English", "Hindi"],
    imdbRating: 8.2,
    rtRating: "90%",
    cineverseRating: 8.6,
    synopsis: "An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/moneyback.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/reKs8aH0VRM6s9xj7v4rV4.jpg",
    moods: ["action_packed", "mind_bending"],
    platforms: [{ id: "netflix", name: "Netflix", price: "Subscription", available: true }],
    cast: [{ name: "Alvaro Morte", role: "The Professor", img: "https://image.tmdb.org/t/p/w185/Alvaro.jpg" }],
    trailerId: "_InqQJRqGW4",
    industry: "webseries"
  },
  {
    id: 39,
    title: "Asur",
    type: "series",
    year: 2020,
    runtime: "2 Seasons",
    genres: ["Crime", "Mystery", "Thriller"],
    languages: ["Hindi"],
    imdbRating: 8.4,
    rtRating: "88%",
    cineverseRating: 8.7,
    synopsis: "A unique psychological thriller that pits forensic science against the mysticism of Indian mythology, amidst a series of bizarre murders.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/asurback.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/asur.jpg",
    moods: ["mind_bending", "slow_burn"],
    platforms: [{ id: "jio", name: "JioCinema", price: "Subscription", available: true }],
    cast: [{ name: "Arshad Warsi", role: "Dhananjay Rajput", img: "https://image.tmdb.org/t/p/w185/Arshad.jpg" }],
    trailerId: "LdKpe19X1y4",
    industry: "webseries"
  },
  {
    id: 40,
    title: "Scam 1992",
    type: "series",
    year: 2020,
    runtime: "10 Episodes",
    genres: ["Drama", "Biography", "Crime"],
    languages: ["Hindi", "English"],
    imdbRating: 9.3,
    rtRating: "97%",
    cineverseRating: 9.5,
    synopsis: "Set in 1980s & 90s Bombay, Scam 1992 follows the life of Harshad Mehta, a stockbroker who took the stock market to dizzying heights & his catastrophic downfall.",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/scamback.jpg",
    posterUrl: "https://image.tmdb.org/t/p/w500/scam1992.jpg",
    moods: ["slow_burn", "feel_good"],
    platforms: [{ id: "sony", name: "SonyLIV", price: "Subscription", available: true }],
    cast: [{ name: "Pratik Gandhi", role: "Harshad Mehta", img: "https://image.tmdb.org/t/p/w185/Pratik.jpg" }],
    trailerId: "2gb9Hj5947M",
    industry: "webseries"
  },
  {
    id: 41,
    title: "Stree 2",
    type: "movie",
    year: 2024,
    runtime: "147 min",
    genres: ["Comedy", "Horror", "Mystery"],
    languages: ["Hindi"],
    imdbRating: 8.0,
    rtRating: "82%",
    cineverseRating: 8.5,
    synopsis: "In the town of Chanderi, a new headless ghost named 'Sarkata' starts abducting women. The townsfolk must once again rely on Vicky and the mysterious Stree to save them.",
    backdropUrl: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=1200",
    posterUrl: "https://image.tmdb.org/t/p/w500/z0T0mQ8s0eFzN1H5S7n1C6H.jpg",
    moods: ["fun_light", "action_packed"],
    platforms: [
      { id: "netflix", name: "Netflix", price: "Subscription", available: true }
    ],
    cast: [
      { name: "Rajkummar Rao", role: "Vicky", img: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100" },
      { name: "Shraddha Kapoor", role: "Stree", img: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100" }
    ],
    trailerId: "x9_hD3Z3j04",
    industry: "bollywood"
  },
  {
    id: 42,
    title: "Animal",
    type: "movie",
    year: 2023,
    runtime: "201 min",
    genres: ["Action", "Drama", "Crime"],
    languages: ["Hindi", "Telugu"],
    imdbRating: 6.8,
    rtRating: "30%",
    cineverseRating: 7.2,
    synopsis: "The complex relationship between a father and son is set against the backdrop of a violent underworld war, driving the son to extreme vengeance.",
    backdropUrl: "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?q=80&w=1200",
    posterUrl: "https://image.tmdb.org/t/p/w500/x2Lw3ku51Z534.jpg",
    moods: ["action_packed", "slow_burn"],
    platforms: [
      { id: "netflix", name: "Netflix", price: "Subscription", available: true }
    ],
    cast: [
      { name: "Ranbir Kapoor", role: "Ranvijay Singh", img: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100" },
      { name: "Anil Kapoor", role: "Balbir Singh", img: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100" }
    ],
    trailerId: "8FkLRUJj-C0",
    industry: "bollywood"
  },
  {
    id: 43,
    title: "Laapataa Ladies",
    type: "movie",
    year: 2024,
    runtime: "122 min",
    genres: ["Comedy", "Drama"],
    languages: ["Hindi"],
    imdbRating: 8.5,
    rtRating: "100%",
    cineverseRating: 9.0,
    synopsis: "The misadventures of two young brides who get accidentally swapped on a train journey, leading to a heartwarming search in rural India.",
    backdropUrl: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?q=80&w=1200",
    posterUrl: "https://image.tmdb.org/t/p/w500/laapataa.jpg",
    moods: ["feel_good", "fun_light"],
    platforms: [
      { id: "netflix", name: "Netflix", price: "Subscription", available: true }
    ],
    cast: [
      { name: "Sparsh Shrivastava", role: "Deepak", img: "https://images.unsplash.com/photo-1489980508314-941910ded1f4?w=100" },
      { name: "Pratibha Ranta", role: "Jaya", img: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=100" }
    ],
    trailerId: "CoM3E8K4J4w",
    industry: "bollywood"
  },
  {
    id: 44,
    title: "Kota Factory",
    type: "series",
    year: 2019,
    runtime: "3 Seasons",
    genres: ["Drama", "Comedy"],
    languages: ["Hindi"],
    imdbRating: 9.0,
    rtRating: "92%",
    cineverseRating: 9.4,
    synopsis: "Set in Kota, Rajasthan, a major coaching hub for IIT-JEE aspirants, this show explores the lives and struggles of student Vaibhav and his friends under the guidance of Jeetu Bhaiya.",
    backdropUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=1200",
    posterUrl: "https://image.tmdb.org/t/p/w500/kotafactory.jpg",
    moods: ["feel_good", "good_cry"],
    platforms: [
      { id: "netflix", name: "Netflix", price: "Subscription", available: true }
    ],
    cast: [
      { name: "Jitendra Kumar", role: "Jeetu Bhaiya", img: "https://image.tmdb.org/t/p/w185/Jitendra.jpg" },
      { name: "Mayur More", role: "Vaibhav Pandey", img: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=100" }
    ],
    trailerId: "pnp_9ZzV8zI",
    industry: "webseries"
  }
];

export const MOCK_REVIEWS = {
  1: [
    { user: "Arjun The Filmmaker", text: "Nolan at his most ambitious. The organ score by Zimmer shook the theater. An absolute masterclass in visual storytelling and emotional depth.", rating: 10, likes: 242 },
    { user: "Riya J", text: "I cried like a baby when Coop watches the videos of his kids growing up. Absolute cinema! 😭 Sci-fi, but fundamentally about a father's love.", rating: 9, likes: 118 }
  ],
  2: [
    { user: "Cinephile99", text: "Deserves every single award. The architectural divide between the families is brilliant. A genre-bending movie that makes you laugh and gasp.", rating: 10, likes: 310 }
  ],
  11: [
    { user: "BollywoodLover", text: "Best movie of all time. Period. Makes you laugh, cry, and change your view on education.", rating: 10, likes: 500 }
  ],
  22: [
    { user: "ActionFanatic", text: "The dance-off and the wild animal scene are pure cinematic adrenaline! Rajamouli does it again.", rating: 10, likes: 420 }
  ],
  31: [
    { user: "SciFiGuy", text: "Perfect retro 80s vibes. Milliy Bobby Brown is amazing as Eleven.", rating: 9, likes: 215 }
  ],
  37: [
    { user: "BryanFan", text: "Walter White is one of the greatest character arcs in television history. Masterpiece.", rating: 10, likes: 300 }
  ]
};
